language: rust
services:
  - postgresql
rust:
  - stable
  - nightly
install:
  - npm install -g elm
  - psql -c 'create database mp;' -U postgres
  #- cd server && cargo install diesel_cli && diesel setup
env:
  - DATABASE_URL=postgres://localhost/mp
matrix:
  allow_failures:
    - rust: stable
script: make ci
