language: generic
sudo: required
dist: trusty
install:
  - curl https://nixos.org/nix/install | sh
  - source $HOME/.nix-profile/etc/profile.d/nix.sh
env:
  matrix:
    - BUILD_PATH=app/default.nix
    - BUILD_PATH=server/default.nix
    - BUILD_PATH=server/stable.nix
script: nix-build $BUILD_PATH
