language: rust
rust:
  - nightly
services:
  - couchdb
env:
  global:
    - DATABASE_URL=http://localhost:5984
    - SERVER_URL=http://localhost:8423
    - SERVER_ADDR=127.0.0.1:8423
install:
  - npm install -g webpack typings n
  - N_PREFIX=$HOME n stable
  - cargo install mdbook
script:
  - pushd lib && cargo build && cargo test && popd
  - pushd app && npm i && typings i && webpack && popd
  - pushd doc && ~/.cargo/bin/mdbook build && popd
