language: rust
sudo: required
dist: trusty
services:
  - postgresql
rust:
  - stable
  - nightly
install:
  - npm install -g elm
  - psql -c 'create database mp;' -U postgres
  - cargo install diesel_cli
  - pushd server && /home/travis/.cargo/bin/diesel migration run && popd
env:
  - DATABASE_URL=postgres://localhost/mp
matrix:
  allow_failures:
    - rust: stable
script: make ci
