language: rust
rust:
  - nightly-2016-03-22
  - nightly
matrix:
  allow_failures:
    - rust: nightly
services:
  - couchdb
env:
  global:
    - DATABASE_URL=http://localhost:5984
    - SERVER_URL=http://localhost:8423
    - SERVER_ADDR=127.0.0.1:8423
install:
  - npm install -g webpack typings n
  - N_PREFIX=$HOME n stable
  - cargo install mdbook
script:
  - pushd server && cargo build && cargo test && popd
  - pushd app && npm i && typings i && webpack && popd
  - pushd docs && mdbook build && popd
