[package]
name = "server"
version = "0.1.0"
authors = ["Jakob Gillich <jakob@gillich.me>"]

[dependencies]
iron = "0.2"
router = "0.1"
logger = "0.0.3"
mount = "0.0.10"
id3 = "0.1"
walkdir = "0.1"
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
rust-crypto = "0.2"
toml = "0.1"
base64 = "0.1"
