[package]
name = "cloudfm-server"
version = "0.1.0"
authors = ["Jakob Gillich <jakob@gillich.me>"]
license = "MIT"

[dependencies]
iron = "0.2"
router = "0.1"
logger = "0.0.3"
mount = "0.0.10"
id3 = "0.1"
walkdir = "0.1"
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
rust-crypto = "0.2"
dotenv = "0.8"
dotenv_macros = "0.8.0"
diesel = "0.5"
diesel_codegen = { version = "0.5.0", default-features = false, features = ["nightly", "postgres"] }
